// <auto-generated />
using LadanANDAsma;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LadanANDAsma.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20210702061610_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LadanANDAsma.entity.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<int>("CustomerPhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("CustomerID");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("LadanANDAsma.entity.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("customername")
                        .HasColumnType("text");

                    b.Property<int>("customernum")
                        .HasColumnType("integer");

                    b.Property<int>("orderdate")
                        .HasColumnType("integer");

                    b.Property<int>("ordernum")
                        .HasColumnType("integer");

                    b.HasKey("orderID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("LadanANDAsma.entity.anbar", b =>
                {
                    b.Property<int>("inventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("inventoryName")
                        .HasColumnType("text");

                    b.HasKey("inventoryID");

                    b.ToTable("anbars");
                });

            modelBuilder.Entity("LadanANDAsma.entity.exit", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("applicantName")
                        .HasColumnType("text");

                    b.HasKey("LicenseID");

                    b.ToTable("exits");
                });

            modelBuilder.Entity("LadanANDAsma.entity.fctor", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IssueDate")
                        .HasColumnType("integer");

                    b.Property<string>("customerAddress")
                        .HasColumnType("text");

                    b.Property<int>("factorID")
                        .HasColumnType("integer");

                    b.Property<string>("productType")
                        .HasColumnType("text");

                    b.HasKey("customerID");

                    b.ToTable("factors");
                });

            modelBuilder.Entity("LadanANDAsma.entity.kala", b =>
                {
                    b.Property<int>("kalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("kalacode")
                        .HasColumnType("integer");

                    b.Property<string>("kalaname")
                        .HasColumnType("text");

                    b.HasKey("kalaID");

                    b.ToTable("kalas");
                });

            modelBuilder.Entity("LadanANDAsma.entity.mojavez", b =>
                {
                    b.Property<int>("licenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("licensedate")
                        .HasColumnType("integer");

                    b.Property<int>("licensenum")
                        .HasColumnType("integer");

                    b.HasKey("licenseID");

                    b.ToTable("mojavezs");
                });

            modelBuilder.Entity("LadanANDAsma.entity.referred", b =>
                {
                    b.Property<string>("referredID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("referredname")
                        .HasColumnType("text");

                    b.HasKey("referredID");

                    b.ToTable("referres");
                });

            modelBuilder.Entity("LadanANDAsma.entity.residKala", b =>
                {
                    b.Property<int>("residID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("date")
                        .HasColumnType("integer");

                    b.Property<int>("residnum")
                        .HasColumnType("integer");

                    b.HasKey("residID");

                    b.ToTable("resids");
                });
#pragma warning restore 612, 618
        }
    }
}
